LineLength:
  Description: 'Limit lines to 130 characters.'
  Max: 130
MethodLength:
  Max: 15
AsciiComments:
  Enabled: false
FrozenStringLiteralComment:
  Enabled: false
AllCops:
  TargetRubyVersion: 2.4
Documentation:
  Enabled: false
ExtraSpacing:
  Enabled: false
IfUnlessModifier:
  Enabled: false
AndOr:
  Enabled: false
SingleLineBlockParams:
  Enabled: false
Style/DotPosition:
  EnforcedStyle: trailing
Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver
  IndentationWidth: 4